### ISSUE TITLE
[API Design] No way to express TLS ciphersuite or protocol restrictions if referencing a Kafka CR

### ISSUE THREAD

**Issue by k-wall** [kroxylicious/design#59]
https://kroxylicious.slack.com/archives/C04V1K6EAKZ/p1741818868349069

@tombentley said:

> a KafkaClusterRef has got spec.tls.protocols and spec.tls.cipherSuites, but it's also proposed for a VirtualKafkaCluster 's spec.targetCluster.clusterRef  to support referencing a Strimzi Kafka CR. In this case, how can the user specify the allowed/denied TLS protocols and cipher suites?

**Comment by tombentley** [comment]
Another thing I find awkward is the UX when we decide to make this work with the [strimzi access operator](https://github.com/strimzi/kafka-access-operator?tab=readme-ov-file#using-the-access-operator). (From a purely API POV I actually prefer this to pointing to a Kafka CR, but in practice the `KafkaAccess` isn't available everywhere). 

The access operator produces a `Secret` (with `type: servicebinding.io/kafka`) containing all the info needed to connect. It seems very natural to want to point to such a `Secret` from a VKC, but:

* That `Secret` includes the client cert and key, so there's nothing for the VKC's `spec.targetCluster.tls`
* There would still be no way for the user to express protocols and cipher suites

If the purpose of the KafkaClusterRef is to have a single place to specify the Kafka connection (to avoid repetition over multiple VCK's) then perhaps it makes sense to commit to KafkaClusterRef fully, but allow it to just point to another resource. In other words the VKC would _always_ point to a `KafkaClusterRef`, and the `KafkaClusterRef` could either specify all the details itself, or reference other resources 

```yaml
kind: VirtualKafkaCluster
spec:
  # ...
  targetKafkaClusterRef:
    name: my-ref
---
kind: KafkaClusterRef
metadata:
  name: my-ref
spec:
  bootstrapServers: # either `bootstrap` or `ref`, and not both
  ref:
    group: kafka.strimzi.io
    kind: Kafka
    namespace: kafka-prod
    name: kafka
  protocol: tls
  nodeRanges: ...
  tls:
    cipherSuites: ...
    protocols: ...
    clientCertificate:
      kind: Secret
      name: kafka-client-cert
    trustAnchor:
      kind: Secret
      name: kafka-client-cert
  ```

The `group` and `kind` of the `connection` would determine what other properties (protocol, nodeRanges, tls.trustAnchor, `tls.clientCertificate` etc) would be required (maybe something we could enforce via CEL validation, if we wanted). For example when linking to a Strimzi `Kafka` the `tls.trustAnchor` would be optional.
